# Generated by Django 5.0.6 on 2024-06-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=64)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Etat', models.BooleanField(default=False)),
            ],
        ),
    ]
