# Generated by Django 5.0.6 on 2024-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0004_remove_tache_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
            ],
        ),
    ]
