# Generated by Django 5.0.6 on 2024-06-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0005_customusercreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserCreation',
        ),
    ]
